import "@/styles/globals.css";

import type { Metadata, Viewport } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";

export const viewport: Viewport = {
	themeColor: "#000000",
};

export const metadata: Metadata = {
	title: "Notifications PWA Test",
	description: "Generated by create-t3-app with PWA and Push Notifications",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
	manifest: "/manifest.json",
	appleWebApp: {
		capable: true,
		statusBarStyle: "default",
		title: "NotifyTest",
	},
	formatDetection: {
		telephone: false,
	},
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html className={`${geist.variable}`} lang="en">
			<body>
				<TRPCReactProvider>{children}</TRPCReactProvider>
			</body>
		</html>
	);
}
